import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        //marginTop: 30,
        flex: 1,
        flexGrow: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        //justifyContent: 'flex-start',
        borderRadius: 0,
        justifyContent: 'center', 
        
      },
      TextZone: {
        top: 0,
        left:0,
        width: 375,
        height: 88,
        flexShrink: 0,
        borderRadius: 24,
        background: 'var(--gradient, linear-gradient(180deg, rgba(0, 0, 0, 0.00) 0%, #000 100%))',
        justifyContent: 'center',
        gap:99,
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 0,
      },
      title: {
        color: '#070A27',
        fontSize: 18,
        //fontFamily: 'Inter',
        fontStyle: 'normal',
        fontWeight: '900',
        lineHeight: 24,
        letterSpacing: -0.54,
        textTransform: 'capitalize',
        position: 'absolute',
        top: 32,
        
      },
      backgroundImage: {
        marginTop: 0,
        width: 343,
        height: 295,
        flexShrink: 0,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 20,
        background: '#FFF',
       marginLeft: 0,
        
      },
      frameContainer: {
        marginTop: 0,
        marginLeft: 16,
        position: 'absolute',
        top: 24,
        left: 0,
        display: 'flex',
        padding:8,
        justifyContent: 'left',
        alignItems: 'center',
        gap: 8,
        borderRadius: 11,
        borderWidth: 1,
        borderColor:  '#FCC433',
        backgroundColor: '#FFF',
      },
      frameImage: {
        width: 24,
        height: 24,
      },
      overlayText: {
        position: 'absolute',
       left: 16,
       top: 20,
       color: '#FFF',
       fontSize: 24,
      // fontFamily: 'Inter',
       fontStyle: 'normal',
       fontWeight: '700',
       lineHeight: 24,
      },
      newText: {
        marginTop: 33,
        fontSize: 18,
       // fontFamily: 'Inter',
        fontWeight: 900,
        lineHeight: 24,
        letterSpacing: -0.54,
        textTransform: 'capitalize',
        color: '#000',
        marginBottom: 16,
        marginLeft: 0,
      },
      p: {
        display: 'flex',
        width: 343,
        flexDirection: 'column',
        flexShrink: 0,
        color: '#595959',
        fontSize: 16,
        //fontFamily: 'Inter',
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: 24,
        fontSize: 16,
        marginBottom: 16,
       marginLeft: 0,
      },
      textZone: {
        top: 80,
        left:0,
        width: 343,
        height: 132,
        flexShrink: 0,
        borderRadius: 24,
        background: 'var(--gradient, linear-gradient(180deg, rgba(0, 0, 0, 0.00) 0%, #000 100%))',
        justifyContent: 'center',
        alignItems: 'center',
      },
      textZoneText: {
        top:11,
        display: 'flex',
        width: 296,
        flexDirection: 'column',
        flexShrink: 0,
        color: '#FFF',
        fontSize: 16,
        //fontFamily: 'Inter',
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: 24,
       
      },
      FrameContainer: {
        position: 'absolute',
        top: 278,
        left: 16,
        padding: 7,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 6,
        borderRadius: 78,
        borderWidth: 2,
        borderColor: '#000',
        backgroundColor: '#FCC433',
        flexDirection: 'row',
        width: 77, 
        height: 35, 
        zIndex: 2,
      },
      image: {
        width: 11,
        height: 11,
        marginRight: 2,
      
      },
      FrameText: {
        color: '#070A27',
        fontSize: 15,
       // fontFamily: 'Inter',
        fontStyle: 'normal',
        fontWeight: '500',
        lineHeight: 18,
        letterSpacing: -0.75,
        textTransform: 'capitalize',
      },
    
      FrameContainer1: {
        position: 'absolute',
        top: 16,
        left: 16,
        padding: 8 ,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 6,
        borderRadius: 78,
        borderWidth: 2,
        borderColor: '#070A27',
        backgroundColor: '#FFF',
        flexDirection: 'row',
        width: 80, 
        height: 35, 
      },
      image1: {
        width: 17,
        height: 17,
        marginRight: 0,
      },
      FrameText1: {
        color: '#212324',
        fontSize: 14,
        //fontFamily: 'Inter',
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: 18,
        letterSpacing: -0.75,
        textTransform: 'capitalize',
      },
      tabBarStyle: {
        bottom: 0,
        left:0,
        right:0,
        width: 395,
        height: 95,
        flexShrink: 0,
        borderRadius: 0,
        background: 'var(--gradient, linear-gradient(180deg, rgba(0, 0, 0, 0.00) 0%, #000 100%))',
        justifyContent: 'center',
        alignItems: 'center',
        gap:41,
        paddingLeft:32,
        paddingRight:35,
        paddingTop:40,
        paddingBottom:20,
      },
      Image: {
        width: 24,
        height: 24,
        marginRight: 2,
        flexShrink: 0,
      },
      FrameContainer2: {
        width: 48,
       height: 48,
       flexShrink: 0,
       borderRadius: 48,
       backgroundColor: '#FCC433',
       backgroundPosition: '-9.236px -5.2px',
       backgroundSize: '138.484% 136.491%',
       backgroundRepeat: 'no-repeat',
       alignItems: 'center',
       justifyContent: 'center',
      },
      Image1: {
        width: 24,
        height: 24,
        marginRight: 2,
      },
      scrollViewContent: {
        flexGrow: 1,
        alignItems: 'center',
        paddingVertical: 20,
        backgroundColor: '#fff',

      },
      miniSwiper: {
        height: 240,
      },
      miniSwiperContainer: {
        borderRadius: 12,
        overflow: 'hidden',
      },
      card: {
        width:  196,
        height: 240,
        flexShrink: 0,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#070A27',
        backgroundColor: '#BBB',
        backgroundPosition: 'center',
        backgroundSize: 'cover',
        backgroundRepeat: 'no-repeat',
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 8,
        bottom:19,
        right:14,
      },
      Zone: {
        bottom:0,
        width: 196,
        height: 70,
        flexShrink: 0,
        borderRadius: 12,
        background: 'var(--gradient, linear-gradient(180deg, rgba(0, 0, 0, 0.00) 0%, #000 100%))',
        right:12,
      },
      city: {
        color: '#FFF',
        //fontFamily: 'Inter',
        fontSize: 16,
        fontStyle: 'normal',
        fontWeight: '900',
        letterSpacing: -0.8,
        textTransform: 'capitalize',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        top:35,
        left:70,
      },
      place: {
        color: '#FFF',
        fontSize: 14,
        fontStyle: 'normal',
        fontWeight: '500',
        letterSpacing: -0.8,
        textTransform: 'capitalize',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        top:10,
        left:8,
        letterSpacing: -0.28,
        lineHeight: 16.8, 
      },
      yellowRectangle: {
        width:188,
        height:230,
      //  flexShrink: 0,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#070A27',
        backgroundColor: '#FCC433',
        top:34,
        left:5,
      },
      cardLarge: {
        width:  196,
        height: 240,
      //  flexShrink: 0,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#070A27',
        backgroundColor: '#BBB',
        backgroundPosition: 'center',
        backgroundSize: 'cover',
        backgroundRepeat: 'no-repeat',
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 8,
        bottom:19,
        right:14,
      },
    
      cardMedium: {
        width: 126,
        height: 121,
       // flexShrink: 0,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#070A27',
        backgroundColor: '#BBB',
        backgroundPosition: 'center',
        backgroundSize: 'cover',
        backgroundRepeat: 'no-repeat',
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 8,
        bottom:20,
        right:16.5, 
        
      },
      triLarge: {
        width: 188,
        height: 230,
       // flexShrink: 0,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#070A27',
        backgroundColor: '#FCC433',
        top:34,
        left:5,
      },
    
      triMedium: {
        width: 114,
        height: 109,
        flexShrink: 0,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#070A27',
        backgroundColor: '#FCC433',
        top:34,
        left:5,
      },
      zLarge: {
        bottom:0,
        width: 196,
        height: 70,
        flexShrink: 0,
        borderRadius: 12,
        right:0,
        left:0,
        top: 85,
      },
      zMedium: {
        bottom:0,
        width: 126,
        height: 51,
       // flexShrink: 0,
        borderRadius: 12,
        left:0,
        bottom:0,
        top:35,
      },
      triSlim: {
        width: 120,
        height: 176,
        flexShrink: 0,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'var(--black, #070A27)',
        backgroundColor: '#FCC433',
      },
    
      cardSlim: {
        width: 132,
        height: 188,
        flexShrink: 0,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#070A27',
        backgroundColor: '#D9D9D9',
      },
    
      zSlim: {
        width: 132,
        height: 62,
        flexShrink: 0,
        borderRadius: '0px 0px 12px 12px',
        top:63,
      },
      txt: {
        marginTop: 0,
        fontSize: 18,
       // fontFamily: 'Inter',
        fontWeight: 900,
        lineHeight: 24,
        letterSpacing: -0.54,
        textTransform: 'capitalize',
        color: '#000',
        marginBottom: 0,
        marginLeft: 0,
        left:0,
        top:0,
      },
      txt1: {
        marginTop: 15,
        marginBottom:7,
        fontSize: 18,
       // fontFamily: 'Inter',
        fontWeight: 700,
        lineHeight: 24,
        letterSpacing: -0.54,
        textTransform: 'capitalize',
        color: '#000',
      },
      lilText: {
        color: '#212324',
       // fontFamily: 'Inter',
        fontSize: 14,
        fontStyle: 'normal',
        fontWeight: '400',
        letterSpacing: -1,
        textTransform: 'capitalize',
        opacity: 0.6,
      },
      gradient: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 12,
      },
      gradient1: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 12,
        width: 343,
      },
      fond: {
        width: 75,
        height: 75,
        flexShrink: 0,
      //  background: 'lightgray 50%' / cover no-repeat',
      },
      FrameContainer3: {
        width: 48,
       height: 48,
       flexShrink: 0,
       borderRadius: 48,
       borderColor: '#070A27',
       backgroundColor: '#E6E6E6',
       borderWidth: 2,
       alignItems: 'center',
       justifyContent: 'center',
      },
      whiteRectangle: {
        width: 343,
        height: 355,
        flexShrink: 0,
        borderRadius: 24,
        borderWidth: 1,
        borderColor: '#070A27',
        backgroundColor: '#FFF',
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 20, 
        paddingHorizontal:16,
        right:10,
        bottom:50,
      },
      yellowRectangle1: {
        width:327,
        height:335,
      //  flexShrink: 0,
        borderRadius: 24,
        borderWidth: 1,
        borderColor: '#070A27',
        backgroundColor: '#FCC433',
        marginVertical: 20, 
        left:10,
        top:30,
      },
    });